'use server';

/**
 * @fileOverview Agent content generation flow.
 *
 * - generateAgentContent - A function that handles the agent content generation process.
 * - AgentContentGenerationInput - The input type for the generateAgentContent function.
 * - AgentContentGenerationOutput - The return type for the generateAgentContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AgentContentGenerationInputSchema = z.object({
  task: z.string().describe('The task to be performed by the agent.'),
  context: z.string().describe('The context for the agent to perform the task.'),
});
export type AgentContentGenerationInput = z.infer<typeof AgentContentGenerationInputSchema>;

const AgentContentGenerationOutputSchema = z.object({
  content: z.string().describe('The content generated by the agent.'),
});
export type AgentContentGenerationOutput = z.infer<typeof AgentContentGenerationOutputSchema>;

export async function generateAgentContent(input: AgentContentGenerationInput): Promise<AgentContentGenerationOutput> {
  return agentContentGenerationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'agentContentGenerationPrompt',
  input: {schema: AgentContentGenerationInputSchema},
  output: {schema: AgentContentGenerationOutputSchema},
  prompt: `You are an AI agent designed to automate content generation tasks.

You are given a task and a context. Perform the task using the context.

Task: {{{task}}}
Context: {{{context}}}

Content:`,
});

const agentContentGenerationFlow = ai.defineFlow(
  {
    name: 'agentContentGenerationFlow',
    inputSchema: AgentContentGenerationInputSchema,
    outputSchema: AgentContentGenerationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
